- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Change Apache port to 81
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: 'Listen 81'
  notify:
    - restart apache
